import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import TanstackProvider from '@/components/TanstackProvider/TanstackProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Note Hub',
  description: 'Generated by GoIt',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TanstackProvider>
          <Header />
          <main>{children}</main>
          <ReactQueryDevtools />
        </TanstackProvider>
        <div id="modal-root"></div>
        <footer>
          <p>
            Created<time dateTime="2025">2025</time>
          </p>
        </footer>
      </body>
    </html>
  );
}
